### ISSUE TITLE
Error 510 - "Not extended" missing

### ISSUE THREAD

**Issue by strangeloveBsc** [rogeriopvl/http.cat#12]
Title says all, I'll try to make it a pull request in time.
Suggested picture for now (still needs the border and text):

![84527717](https://user-images.githubusercontent.com/3050149/33658179-aac5fd5a-da73-11e7-8f4d-6bed9014a166.jpg)

**Comment by rogeriopvl** [comment]
@strangeloveBsc That's actually a pretty good one 😸 

cc @girliemac

**Comment by strangeloveBsc** [comment]
I couldn't guess the font, but the picture is perfectly aligned with the original box.
![ne](https://user-images.githubusercontent.com/3050149/33681663-7f655cda-dac5-11e7-92d4-d2248d30b25e.png)

**Comment by girliemac** [comment]
LOL, that's the Google Maps kitty 😂 
BTW, I used this motivational poster maker originally: https://bighugelabs.com/motivator.php

**Comment by rogeriopvl** [comment]
@girliemac thanks for sharing!

@strangeloveBsc Can you do a pull request with that? I'll be glad to merge it!
