### ISSUE TITLE
need to switch to https

### ISSUE THREAD

**Issue by girliemac** [rogeriopvl/http.cat#17]
People are getting the "Your connection is not private" message on Chrome. Thank you!

**Comment by girliemac** [comment]
(and nope, I am not suggesting to make it HTTPS Cat 😉 )

**Comment by maracuja-juice** [comment]
Just checked: It is https but the certificate expired yesterday!

**Comment by rogeriopvl** [comment]
Thanks for the heads up everyone ☺️ Fixed!

**Comment by maracuja-juice** [comment]
Nice. You should automate this btw.
