### ISSUE TITLE
Compress images using TinyPNG

### ISSUE THREAD

**Issue by ushuz** [rogeriopvl/http.cat#2]
![image](https://cloud.githubusercontent.com/assets/1430856/11989872/691f88cc-aa40-11e5-9382-08991ffe90b4.png)

For example, `400.jpeg` could be compressed from 120kb to about 50kb, nearly 60% smaller, without noticeable quality loss. It could save some bandwidth both for https://http.cat and for people who reference those cute cat images.

Take a look at: https://tinypng.com/ , they are good at compressing images, and have an API for that. Their API is free for the first 500 images in a month, it's quite enough for https://http.cat I think.

If you are interested, I can open a pull request.

**Comment by rogeriopvl** [comment]
Thanks @ushuz. If you wish you can open a PR. But the API suggestion won't work, http.cat serves around 1 Million images a month :)

**Comment by ushuz** [comment]
@rogeriopvl Sorry, my mention about API is a little bit misleading. What I really meant is that with their API and 500 quota, compressing all 51 cat images can be easily done.

I opened a pull request #3 , images are now ~50% smaller on average.

**Comment by rogeriopvl** [comment]
Closed via #3
