### ISSUE TITLE
504 gateway timeout is missing

### ISSUE THREAD

**Issue by mxmo0rhuhn** [rogeriopvl/http.cat#6]
The 504 cat is missing even though it is available on [flickr](https://www.flickr.com/photos/girliemac/25362894310/in/album-72157628409467125/). 

Is there a problem with copyright or are pull requests welcome?

**Comment by rogeriopvl** [comment]
Hey @mxmo0rhuhn , I've been kind of busy, but I'll add the picture ASAP! Thanks!

**Comment by mxmo0rhuhn** [comment]
Thanks a lot! I'm looking forward to it :+1:

**Comment by maracuja-juice** [comment]
@mxmo0rhuhn The image was added in last October. I think this issue can be closed.
